### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by aloneuser** [zen-tools/gxkb#16]
Спасибо за единственный нормальный переключатель раскладок

**Comment by zen-tools** [comment]
Дякую, дуже приємно це чути! :slightly_smiling_face: 
Але краще притримуватись англійської мови, тому що це місце для міжнародного спілкування.
___
Спасибо, приятно это слышать! :slightly_smiling_face: 
Но лучше придерживаться английского языка, так как это место для международного общения.
___
Thanks, nice to hear that! :slightly_smiling_face: 
But it's better to talk in English, because it's a place for international communication.
