### ISSUE TITLE
cli or signals

### ISSUE THREAD

**Issue by paperbenni** [zen-tools/gxkb#26]
This is a feature request. It would be awesome if there was some way to use gxkb other than clicking or scrolling on the applet. What I have in mind are either signals sent to the applet to either switch to the next layout or open the menu, or  a cli option to do just that. Or implement a dbus interface. Either way it would allow external tools to interact with gxkb and you could for example to a keybind that reproduces the layout switcher on windows.

**Comment by zen-tools** [comment]
Hi! I would like to keep gxkb as simple as possible. But I can suggest to take a look at  [xkbmon](https://github.com/xkbmon/xkbmon)+[xkb-switch](https://github.com/grwlf/xkb-switch) utils. If your window manager supports lua-scripting, you may use these tools to get a list of available keyboard layouts, current keyboard layout and switch keyboard layout. And gxkb can work as usual in order to remember keyboard layouts by application/window.
