### ISSUE TITLE
[Wishlist] Port to GTK3

### ISSUE THREAD

**Issue by mati75** [zen-tools/gxkb#29]
Debian want to remove gtk2 applications. In this case I created this issue and my simple patch in pull (https://github.com/zen-tools/gxkb/pull/28).

Patch is working but with a few issues, in my test in lxqt left mouse click menu is not displayed.

**Comment by zen-tools** [comment]
Hi! Thanks for the patch, it really helps. Regarding the issue with left mouse click, let me guess do you have only two layouts? If so, it's correct behavior. gxkb shows a menu if your system is configured to use 3 and more layouts (and that works fine on my PC with openbox+tint2).

Except a lot of deprecated functions, I have found only one minor issue - there is no tooltip on the systray icon. But that may be 
 related to my PC's settings, because all other GTK3 applications also do not show tooltips... But right now it's not important. Thanks again for the help! :slightly_smiling_face:
