### ISSUE TITLE
Every time I connect to a Bluetooth device it gets switched to GB layout and any other missing

### ISSUE THREAD

**Issue by b0tm1nd** [zen-tools/gxkb#47]
Once I connect to a Bluetooth device, all my layouts disappear and getting a GB only (which I dont even have before this happens).
And need to restart to get them all back.
gxkb version 0.9.3-1 on Debian 12
![2024-06-20_00-39](https://github.com/zen-tools/gxkb/assets/3400283/3870d37f-d702-403f-a6dc-0a43ac495282)

**Comment by b0tm1nd** [comment]
When I was reconnecting to a Bluetooth / restarting gxkb for quite a while while writing the above message (to get all the versions and a screenshot) I ended up my configuration .config/gxkb/gxkb.cfg got reset having only a gb layout and toggle_option empty.
This happened for the first time that I had to manually put back all my layouts into configuration.

**Comment by zen-tools** [comment]
Hi!

I did reproduce the issue, but the strange thing is the issue appears even if `gxkb` is not running. It's as if `Xorg` returns the keyboard configuration from the `/etc/default/keyboard` file instead of the actual keyboard configuration that you can set at any point in time using the `setxkbmap` command.

I will see if that can somehow be fixed on the `gxkb` side, but until then, you could try a workaround from [this](https://github.com/zen-tools/gxkb/issues/45#issuecomment-2073401003) message.

**Comment by b0tm1nd** [comment]
Hello.

Thanks, following the workaround and editing `/etc/X11/xorg.conf.d/00-keyboard.conf` with my layouts/toggle and setting `never_modify_config=true` solved it!
